### PR TITLE
chore: directory structure

### PR DESCRIPTION
**Pull request by crherman7**
## Scope

NOTICKET

## Implementation

To fit more of a standard with other monorepos anything that uses the library or is external the library that is running an application will go under apps/ and other stuff that are packages will go under packages/.

## Screenshots

<details>
  <summary>ios</summary>

  

Simulator Screenshot - iPhone 15 - 2024-09-09 at 21 31 14
</details>

<details>
  <summary>android</summary>
  
  

Screenshot_1725931921
</details>

## How to Test

- run the example app

## Emoji Guide

**For reviewers: Emojis can be added to comments to call out blocking versus non-blocking feedback.**

E.g: Praise, minor suggestions, or clarifying questions that don’t block merging the PR.

> 🟢 Nice refactor!

> 🟡 Why was the default value removed?

E.g: Blocking feedback must be addressed before merging.

> 🔴 This change will break something important

| | | |
| --- | --- | --- |
| Blocking | 🔴 ❌ 🚨 | RED |
| Non-blocking | 🟡 💡 🤔 💭 | Yellow, thinking, etc |
| Praise | 🟢 💚 😍 👍 🙌 | Green, hearts, positive emojis, etc |

### CODE REVIEW

**Comment by crherman7** [comment]
Need to update .gitignore

**Comment by crherman7** [comment]
Simulator Screenshot - iPhone 15 - 2024-09-10 at 13 33 05

getting this in react-native app

**Comment by crherman7** [comment]
resolved

**Review by devs9 — APPROVED** [review]
🟢  Awesome job!

**Pull request merged**
